cron_text = <<-EOS
# DO NOT EDIT THIS MANUALLY
# BECAUSE THIS IS AUTO GENERATED BY Itamae
0 0 1 * * #{node[:letsencrypt][:cron_user]} #{node[:letsencrypt][:certbot_auto_path]} renew
EOS

execute "echo '#{cron_text}' > #{node[:letsencrypt][:cron_file_path]}"

service "cron" do
  action :start
end
